name: Proton PR Checks
 
on:
  pull_request:
 
jobs:
  check:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/loom-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }} # I do this because I don't want each check to take too much time
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run checkstyle
      run: ./gradlew check
